### ISSUE TITLE
not picking up html changes

### ISSUE THREAD

**Issue by ryandm** [meteor-velocity/node-soft-mirror#25]
Hey @Sanjo I could see this being a known issue -- filing this anyway in case it helps. I'm a noob so it tripped me up a bit :)

Repro by running `meteor create app`, adding a test for the value of `document.title`, opening localhost:3000 and localhost:5000 side by side, and trying to make the test pass by changing `app.html` (doesn't work) vs. changing `app.js` (works).

Commands:

```
ryandm@laptop ~ $ meteor create app
app: created.                                 

To run your new app:                          
  cd app                                      
  meteor                                      
ryandm@laptop ~ $ cd app                      
ryandm@laptop ~/app $ meteor add coffeescript mike:mocha

Changes to your project's package version selections:

amplify                    added, version 1.0.0
coffeescript               added, version 1.0.5
less                       added, version 1.0.12
mike:mocha                 added, version 0.5.1
practicalmeteor:chai       added, version 1.9.2_3
practicalmeteor:loglevel   added, version 1.1.0_3
velocity:core              added, version 0.4.5
velocity:html-reporter     added, version 0.3.2
velocity:node-soft-mirror  added, version 0.2.4
velocity:shim              added, version 0.1.0
velocity:test-proxy        added, version 0.0.4


coffeescript: Javascript dialect with fewer braces and semicolons
mike:mocha: Run mocha tests in the browser    
ryandm@laptop ~/app $ mkdir -p tests/mocha/client
ryandm@laptop ~/app $ cat >tests/mocha/client/title.coffee <<'EOF'                   
MochaWeb.testOnly ->
  describe "the title", ->
    it "is foobar", ->
      chai.assert.equal "foobar", document.title
EOF
```

At this point run meteor, and open localhost:3000 and localhost:5000. The app.html change below doesn't pass the tests (unless meteor is restarted) but the app.js change does pass the tests (even if meteor isn't restarted).

```
ryandm@laptop ~/app $ perl -pi -e 's:app:foobar:' app.html
ryandm@laptop ~/app $ cat >>app.js <<'EOF'
if (Meteor.isClient) {
  document.title = 'foobar';
}
EOF

```

Also, not sure it matters, but here's what I'm running:

```
ryandm@laptop ~ $ meteor --version
Meteor 1.0.2.1
ryandm@laptop ~ $ node --version                                                     
v0.10.33
ryandm@laptop ~ $ uname -a
Linux laptop 3.16.0-24-generic #32-Ubuntu SMP Tue Oct 28 13:13:18 UTC 2014 i686 i686 i686 GNU/Linux
```

**Comment by Sanjo** [comment]
Hi, thanks for reporting this issue. I wonder if this is also a problem in sanjo:jasmine. Would be awesome if you could try your case with sanjo:jasmine too and report back if the same issue exists with sanjo:jasmine.

**Comment by ryandm** [comment]
Yes, I see the same behavior with sanjo:jasmine. Out of fear that my inexperience here causes me to summarize what happened inaccurately, here's some detail regarding what I did:

1. Same setup as above except install `sanjo:jasmine velocity:html-reporter` instead of `mike:mocha`.
2. Click "Add jasmine-client-integration sample tests" in the UI to make some directories.
3. Put the following content in tests/jasmine/client/integration/sample/spec/title.coffee and test html-change vs. js-change as for `mike:mocha`.
```
describe 'the title', ->
  it 'is foobar', ->
    expect(document.title).toEqual 'foobar'
```

**Comment by samhatoum** [comment]
This is probably the best bug report I've seen to date here, so thank you for taking the time to put all this work together. I can replicate the issue perfectly. 

It seems that the issue is not that HTML file changes are not being picked up, I just tested the same thing above but with some content under the body tags. That works fine. It's to do with the `head` of the document not being updated on the mirror from the HTML file, but it is happening from JS.

Why?... now the hard part!

**Comment by samhatoum** [comment]
looking at `cat .meteor/local/build/programs/web.browser/head.html`, I can see the file is being updated after Meteor detects changes, and I can also see the mirror restarting ([because of this](https://github.com/meteor-velocity/node-soft-mirror/blob/develop/mirrorClientUpdater.js#L66)). So the issue is that when the `head.html` file changes, and node is running, a browser refresh is not enough and currently a node-soft-mirror server restart is required.

@Sanjo any ideas?

**Comment by samhatoum** [comment]
Ok, the issue is more complicated yet! 

The file '.meteor/local/build/programs/web.browser/head.html' is not the issue, it seems that Meteor serves a head file that you can see by viewing the source of:

`localhost:5000`

This is not being refreshed on the mirror once node is up. It also contains a link to a randomly generated number css filename, like: `/86020907354dc9f93a7b2637aa2e87136c7e4824.css`. When a CSS change happens, this filename changes and the mirror gets an error 500 trying to request the older file.

Solutions I see are:

a) actually restart the mirror process on client changes (just like the server)
b) find a way to poke the running node process to update the head

**Comment by samhatoum** [comment]
c) start a new mirror for every test run, then kill the mirror after all tests are complete.

**Comment by ryandm** [comment]
(Closing as old/stale.)
